### ISSUE TITLE
No support for rendering IE conditional comments

### ISSUE THREAD

**Issue by karlhe** [ageweke/fortitude#23]
See http://www.quirksmode.org/css/condcom.html

Erector supported this type of comment as a block comment.

Currently can workaround this like so:

    rawtext ''

**Comment by ageweke** [comment]
Karl,

First off — my apologies for the long delay. I'm actually currently hiking the Pacific Crest Trail, and so will be slow to respond (and not really in a position to do any coding) for the next five months or so.

I'm reluctant to add very special-purpose features like this to Fortitude…it's obviously pretty easy to build stuff like this just using the native #comment method, and you can customize it to your own precise needs. Erector always had a lot of syntactic sugar for things that, in my opinion, weren't always clearly necessary. (For example, just for me, features like this one were something I used rarely enough that I had to look up the exact syntax every time anyway…at which point it was probably easier to just use the raw comment syntax, anyway.)

Having said that, if someone wanted to build a "fortitude-erector-compat" gem (or something similar) that, for example, defined a FortitudeErectorCompat::Base subclass of Fortitude::Widget that added all that stuff in, that'd obviously be extremely useful to Erector users, and I'd be more than happy to link to it from relevant places in the (largely upcoming) Fortitude docs. If it's not already there by the time I get back, I'd be happy to work on it myself, too. I'm a big fan of this kind of code existing, in other words — I'm just not sure it necessarily should go into the Fortitude core. (I imagine in not so many years, those IE conditional comments will largely disappear from the Web entirely, as IE 6/7/8/etc. finally become relics of the past. But if we add this stuff to Fortitude, we can really never remove it without breaking compatibility, and that would suck.)

Anyway, that's my (long-winded) 2¢ on the topic. Hope that helps. Thanks for using Fortitude, and, if anything else comes up, I'd be more than happy to help in any way I can!

  Thanks,
   Andrew

**Comment by karlhe** [comment]
Indeed, I only mentioned it because I thought it was a rather commonplace syntax to use, but you're right that the need for it is dying out.
