### ISSUE TITLE
Rails generator support…

### ISSUE THREAD

**Issue by Gaelan** [ageweke/fortitude#25]
…would be great! This isn't an extremely high-priority feature, but generators are one of the things that really make Rails development a joy.

**Comment by ageweke** [comment]
Gaelan,

Thanks for the request! I've thought about Rails generators, but haven't gotten there yet. Is there a particular scenario you have in mind? i.e., when you type X, what should Fortitude generate into what files?

Also, just as a heads-up: I am hiking the Pacific Crest Trail this summer and so likely won't be able to tackle this for a while — but it is definitely something I want to get in there for a 1.0 release. So thanks for posting the report!

  Cheers,
   Andrew

**Comment by ageweke** [comment]
@Gaelan — I'm back from hiking the PCT, and am resuming active Fortitude development. 

I'd love to add Rails generator support, although it's still not entirely clear to me exactly how it should behave. Any thoughts?

**Comment by ageweke** [comment]
Closing this, as it’s old and it’s not totally clear what’s desired.

**Comment by Gaelan** [comment]
Bah, I keep forgetting to get to this. I'm thinking of something similar to (Rails's default ERB generators)[https://github.com/rails/rails/tree/master/railties/lib/rails/generators/erb]--when a controller or scaffold is generated, automatically generate basic Fortitude views as placeholders.
