### ISSUE TITLE
static with varying

### ISSUE THREAD

**Issue by leafo** [ageweke/fortitude#26]
It would be cool if you could specify a list of needs that `static` caching could vary on. For example we want to cache some widgets but we also render them in different locales, so it would be nice to say something like:

```ruby
static :html_content, varies: [:locale]
```

or something similar. Then for each value of locale that the widget renders from would use a different cache

**Comment by ageweke** [comment]
Leafo — sorry for the long delay. I think I mentioned that I was hiking the Pacific Crest Trail all summer, and development is hard to do with an iPhone in the backwoods. I finished a few days ago (all 2,650 miles, yeah!) and am increasingly back in civilization. Fortitude development should be back on track shortly.

So, `static` _should_ automagically [be smart enough to respect `locale`](https://github.com/ageweke/fortitude/blob/master/lib/fortitude/support/staticized_method.rb#L18-L19) already. If you're not seeing that behavior, please let me know.

As for more-general `varies` support: I really like the idea you have above, and considered it during development. I do have one concern, however. Right now, `static` generates content lazily, then simply caches it in a `Hash`, keyed by the widget locale (or just `nil` if none is set). There's no expiration mechanism or limit to this cache. I think this is likely good enough for now (although I do have occasional concerns about it being a potential DoS attack, if HTTP clients can pass in totally arbitrary locales — I don't yet know if Rails restricts that or not). 

If I added arbitrary `varies` support, it suddenly becomes a whole lot easier to accidentally create long-term, nasty memory leaks in your application, if you add a `varies` that depends on something that can, well, vary too much. At some point, you're much better off just using Rails' built-in view fragment caching mechanisms, which have pluggable backends and can expire old content, limit the amount of data kept, share it among processes, and so on.

Any thoughts on what the correct balance is? Or does the automagic behavior for `locale` take care of your problem well enough?

**Comment by leafo** [comment]
Ah, I hadn't see the `widget_locale` stuff when I was working on this. I haven't had a need to do static with varying any other time yet, so definitely not a critical feature for me. I understand your fear of the implications that come with adding more complex caching though.

Maybe your static implementation can be built on top of rails' fragment caching? So you can get all the additional functionality it provides.

**Comment by ajb** [comment]
I think I'm looking for the same thing in issue #9, just calling it by a different name.

**Comment by ajb** [comment]
Hey @leafo,

> Maybe your static implementation can be built on top of rails' fragment caching? So you can get all the additional functionality it provides.

I've got a WIP of this in https://github.com/ageweke/fortitude/pull/39; would appreciate some feedback if you have a sec!

**Comment by ageweke** [comment]
I’m gonna close this for now — it’d be great to fold discussion in under PR #54. :)
