### ISSUE TITLE
Allow customizing view paths?

### ISSUE THREAD

**Issue by karlhe** [ageweke/fortitude#27]
I'm using a few custom defined view paths, without going into too much detail I need to look in various `<path>/app/views` in addition to the standard `app/views` path.

I have a works-for-me hacked-up version of this available here: https://github.com/bigfix/fortitude/commit/f8aa0ed29fd2a7a8d68f08c160686ab94671a2cf

It looks at the Rails paths configuration variable for `app/views` to pull a list of view paths to use, then loops over the old code to include files from all such locations.

**Comment by ageweke** [comment]
Thanks, Karl! Many apologies for the long delay — I was through-hiking the [Pacific Crest Trail](https://en.wikipedia.org/wiki/Pacific_Crest_Trail) all summer, and just completed it a few days ago. It's pretty hard to do development from your iPhone in the backwoods, but now I'm back in civilization (or pretty close). One of my first priorities is going to be to drive Fortitude to 1.0.0, which basically means fixing any bugs people have reported, adding any missing features anybody's discovered, and completing the docs.

I'll take a look at your changes in the next few days, and pull them in if at all appropriate. Thanks so much for letting me know about this!

**Comment by ageweke** [comment]
Thanks so much for all this work, Karl. All view paths should work properly now.
