### ISSUE TITLE
Unit testing of widgets?

### ISSUE THREAD

**Issue by jdickey** [ageweke/fortitude#28]
With Erector, as demonstrated in their [specs](https://github.com/erector/erector/blob/master/spec/erector/widget_spec.rb), testing widgets using `#to_html`, `#to_a`, etc, was drop-dead simple. Writing simple tests like

```ruby
    it 'renders the expected content' do
      expect(FooWidget.new.to_html).must_equal expected_content
    end
```

would Just Work. Fortitude adds an internal, apparently-undocumented rendering context that leads the above MiniTest::Spec code to fail with the obviously-intended-to-be-helpful message

    Fortitude::Errors::NoBlockToYieldTo: You're trying to call 'yield' (or 'yield_from_widget', or the Erector-compatibility method 'call_block')
    from the widget #<Views::FooWidget:xxxxxxxx>; however, there is nothing to yield to. Fortitude
    looks for something to yield to in this order:
      1. A block passed to a yield at render time directly (usually via the 'widget' call);
      2. A block passed to the constructor of the widget;
      3. The layout the widget is being rendered in.
    None of these exist here, and so calling 'yield', 'yield_from_widget', or 'call_block' is an
    undefined operation.

So what should I be doing instead to unit-test a widget? Isn't the whole *point* of "Views Are Code" supposed to be that we can treat widgets and widget-derived code like pages the same as any other classes in our system — with testing, composition, SOLID, and so on?  Of *course* feature specs work, but that's only *half the job*.

What has everybody else been doing?

**Comment by karlhe** [comment]
What do the contents of that widget look like?

I just tried what you mentioned on one of my simpler widgets and it works fine:

```
irb(main):020:0> Views::Widgets::Base.new.to_html
=> "<!-- BEGIN Views::Widgets::Base depth 0: :id => (DEFAULT) nil, :element => (DEFAULT) nil, :classes => (DEFAULT) nil -->\n<div id=\"u9iydhwl\" class=\"\">\n</div>\n<!-- END Views::Widgets::Base depth 0 -->"
```

**Comment by alexch** [comment]
One thing I've noticed about Fortitude is that its rendering model
isn't quite as clean as Erector's. There are times when you need to
use `capture`, or when it depends on some context that hasn't been set
up yet.

is Jumbotron a layout or have dependencies on some other widget?

Can you capture the `Fortitude::Errors::NoBlockToYieldTo` backtrace
and see who's calling yield?

(P.S. Hi Jeff! :-))

**Comment by jdickey** [comment]
@karlhe, take a look at [this Gist](https://gist.github.com/jdickey/29bac445745734c174a0) that I wrote up and attached the relevant files' contents to, as well as the error dump that prompted filing of this issue.

Note the update at the bottom of the intro, where I document discovery of a workaround that indeed allows me to unit test widgets that yield to blocks if specified — by wrapping the widget of interest in a dummy widget. Ceremonious overkill? Absolutely. Can I think of a better way to do it, *that actually works?* Nope.

**Comment by jdickey** [comment]
Hey, @alexch, how's life? Your questions should be answered by that [Gist](https://gist.github.com/jdickey/29bac445745734c174a0) I linked to in my answer to @karlhe.

**Comment by ageweke** [comment]
I'm reopening this, at least temporarily. It strikes me that Fortitude might be breaking `#block_given?` in a widget context, and that would be bad. At minimum, I want to write some specs around this to make sure it's completely solid (and stays that way). I'll also make sure there aren't some weird situations in which `MyWidget.new.to_html` doesn't work for some reason. I very much want Fortitude widget testing to Just Work. :)

**Comment by ageweke** [comment]
There was, in fact, an issue here underneath: `#block_given?` always returned `true` inside a Fortitude widget's `content` method, whether or not there was any block passed anywhere. Fixed now.
