### ISSUE TITLE
How to access (Rails controllers') flash messages?

### ISSUE THREAD

**Issue by jdickey** [ageweke/fortitude#29]
Erector's Rails integration, IIRC, gave you a `controller` accessor that you could call `#flash` on to retrieve flash messages. I've been stumped for a full day on how to access flash messages inside a Fortitude page widget. What am I missing?

**Comment by ajb** [comment]
Hmm, I'm looking at our one app that uses Fortitude, and it looks like
we're just calling `flash` as you would in ERB. Does that not work?

On Thu, Jul 23, 2015 at 10:14 AM, Jeff Dickey <notifications@github.com>
wrote:

> Erector's Rails integration, IIRC, gave you a controller accessor that
> you could call #flash on to retrieve flash messages. I've been stumped
> for a full day on how to access flash messages inside a Fortitude page
> widget. What am I missing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ageweke/fortitude/issues/29>.
>



-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker

**Comment by jdickey** [comment]
Odd… I just read where `extra_assigns` is [documented](https://github.com/ageweke/fortitude/blob/master/README-erector.md#set-options-for-backwards-compatibility) after having it not catch my eye the first *n* times I read through the doc. Flash works *if* you set `extra_assigns` to `:use`.

Adding a note to the paragraph starting out

> `extra_assigns :use` says "if passed assignments...

would probably be a Good Thing; something on the order of

> `extra_assigns :use` says "if passed assignments that I haven't needed, make them available anyway, instead of ignoring them. This also pulls in features such as Rails' flash messages that aren't (generally thought of as, at least) instance variables on the controller itself."

**Comment by jdickey** [comment]
Actually, I notice that setting `implicit_shared_variable_access` to `true` will have the same effect; can you describe why one would be chosen over the other for something like this?

**Comment by ajb** [comment]
Oh, I'm not a collaborator on this repo, just an early user. I'm sure @ageweke will chime in when he's back from his trip.

**Comment by jdickey** [comment]
ah, cool; many thanks indeed.

**Comment by ageweke** [comment]
@jdickey — I'm back from my hike, and taking a look into this. Thanks for the edit. I've never used MiniTest before. If you write a MiniTest unit test, and use ERb (as opposed to Fortitude), does `flash` work?

My goal is to make Fortitude behave identically to ERb in this sort of situation. Also, `extra_assigns :use` is really intended as a workaround for old, messy views; it carries a performance penalty out of necessity, and makes it easier to make mistakes. I don't want people to have to turn it on unless they have a lot of really grungy views that make it nearly impossible to reasonably write `needs` declarations for them.

**Comment by ageweke** [comment]
(Reopening this until I make sure I've got any issues here absolutely nailed.)

**Comment by ageweke** [comment]
I’m pretty convinced, after looking back over this, that it’s basically the same issue as #34: it’s all about the testing environment. You can’t just `.new.html` a Fortitude widget in any arbitrary test (whether MiniTest or RSpec or anything else) and have it have access to Rails integration (variables, helpers, _etc._), any more than you can just use the raw ERb library to evaluate a `.html.erb` file and have it have access to Rails integration either. It’s all about the controllers. There’s a very long comment I left on #34 that hopefully makes it all crystal-clear (or even more muddy ;) )…

**Comment by jdickey** [comment]
Agreed, and thanks again for the discussion on #34.
