### ISSUE TITLE
Upgraded to Rails 4.2.5.2 and everything is blowing up

### ISSUE THREAD

**Issue by gleenn** [ageweke/fortitude#44]
I get this or similar stack trace on every test and every page render attempt. I attached my Gemfile too and am using ruby-2.3.0.

ArgumentError (wrong number of arguments (given 5, expected 4)):
  fortitude (0.9.4) lib/fortitude/rails/railtie.rb:251:in `find_templates_with_fortitude'
  actionview (4.2.5.2) lib/action_view/template/resolver.rb:116:in `block in find_all'
  actionview (4.2.5.2) lib/action_view/template/resolver.rb:152:in `block in cached'
  actionview (4.2.5.2) lib/action_view/template/resolver.rb:63:in `cache'
  actionview (4.2.5.2) lib/action_view/template/resolver.rb:151:in `cached'
  actionview (4.2.5.2) lib/action_view/template/resolver.rb:115:in `find_all'
  actionview (4.2.5.2) lib/action_view/path_set.rb:70:in `block (2 levels) in _find_all'
  actionview (4.2.5.2) lib/action_view/path_set.rb:66:in `each'
  actionview (4.2.5.2) lib/action_view/path_set.rb:66:in `block in _find_all'
  actionview (4.2.5.2) lib/action_view/path_set.rb:65:in `each'
  actionview (4.2.5.2) lib/action_view/path_set.rb:65:in `_find_all'
  actionview (4.2.5.2) lib/action_view/path_set.rb:54:in `find_all'
  actionview (4.2.5.2) lib/action_view/path_set.rb:46:in `find'
  actionview (4.2.5.2) lib/action_view/lookup_context.rb:121:in `find'
  actionview (4.2.5.2) lib/action_view/renderer/abstract_renderer.rb:18:in `find_template'
  actionview (4.2.5.2) lib/action_view/renderer/template_renderer.rb:40:in `determine_template'
  actionview (4.2.5.2) lib/action_view/renderer/template_renderer.rb:8:in `render'
  actionview (4.2.5.2) lib/action_view/renderer/renderer.rb:46:in `render_template'
  actionview (4.2.5.2) lib/action_view/renderer/renderer.rb:27:in `render'
  actionview (4.2.5.2) lib/action_view/rendering.rb:100:in `_render_template'
  actionpack (4.2.5.2) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.2.5.2) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (4.2.5.2) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.2.5.2) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.5.2) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.2.5.2) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.2.5.2) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (4.2.5.2) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /Users/glenn/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
  activesupport (4.2.5.2) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.2.5.2) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (4.2.5.2) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (4.2.5.2) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.2.5.2) lib/action_controller/metal/instrumentation.rb:43:in `render'
  fortitude (0.9.4) lib/fortitude/rails/rendering_methods.rb:85:in `render_with_fortitude'
  actionpack (4.2.5.2) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  actionpack (4.2.5.2) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
  actionpack (4.2.5.2) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.5.2) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.5.2) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.5.2) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.5.2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.5.2) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.5.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.5.2) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.5.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.5.2) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.5.2) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.5.2) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.5.2) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.5.2) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.5.2) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.5.2) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.5.2) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.5.2) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.5.2) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.5.2) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.5.2) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.5.2) lib/action_dispatch/routing/route_set.rb:815:in `call'
  xray-rails (0.1.18) lib/xray/middleware.rb:38:in `call'
  omniauth (1.3.1) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.3.1) lib/omniauth/strategy.rb:164:in `call'
  omniauth (1.3.1) lib/omniauth/builder.rb:63:in `call'
  meta_request (0.3.4) lib/meta_request/middlewares/app_request_handler.rb:13:in `call'
  meta_request (0.3.4) lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.5.2) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.5.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.5.2) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  airbrake (4.3.5) lib/airbrake/rails/middleware.rb:13:in `call'
  rack-contrib (1.4.0) lib/rack/contrib/response_headers.rb:17:in `call'
  meta_request (0.3.4) lib/meta_request/middlewares/headers.rb:16:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (3.1.1) lib/web_console/middleware.rb:131:in `call_app'
  web-console (3.1.1) lib/web_console/middleware.rb:28:in `block in call'
  web-console (3.1.1) lib/web_console/middleware.rb:18:in `catch'
  web-console (3.1.1) lib/web_console/middleware.rb:18:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.5.2) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.5.2) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.5.2) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.5.2) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.5.2) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.5.2) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.5.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  airbrake (4.3.5) lib/airbrake/user_informer.rb:16:in `_call'
  airbrake (4.3.5) lib/airbrake/user_informer.rb:12:in `call'
  railties (4.2.5.2) lib/rails/engine.rb:518:in `call'
  railties (4.2.5.2) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  puma (2.16.0) lib/puma/server.rb:557:in `handle_request'
  puma (2.16.0) lib/puma/server.rb:404:in `process_client'
  puma (2.16.0) lib/puma/server.rb:270:in `block in run'
  puma (2.16.0) lib/puma/thread_pool.rb:106:in `block in spawn_thread'

Gemfile:

source 'https://rubygems.org'
ruby '2.3.0'

gem 'airbrake', '< 5'
gem 'coffee-rails'
gem 'compass-rails', '< 3'
gem 'ethereum'
gem 'faye-websocket'
gem 'fortitude'
gem 'foundation-icons-sass-rails'
gem 'foundation-rails', '< 6'
gem 'jbuilder'
gem 'jquery-rails'
gem "nilify_blanks"
gem 'nokogiri'
gem 'omniauth-slack'
gem 'omniauth'
gem 'pg'
gem 'postmark-rails'
gem 'premailer-rails'
gem 'puma'
gem 'pundit'
gem 'rails_12factor', group: :production
gem 'rails', '4.2.5.2'
gem "refile", require: "refile/rails"
gem "refile-mini_magick"
gem "refile-s3"
gem 'responders'
gem 'sass-rails'
gem 'sdoc',          group: :doc
gem 'slack-ruby-client'
gem 'sucker_punch'
gem 'uglifier'

group(:test) do
  gem 'webmock'
  gem 'vcr'
end

group(:development, :test) do
  gem 'awesome_print'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'dotenv-rails'
  gem 'faker'
  gem 'fuubar'
  gem 'guard-rspec', require: false
  gem 'phantomjs', require: 'phantomjs/poltergeist'
  gem 'poltergeist'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'rack_session_access'
  gem 'rspec-rails'
  gem 'selenium-webdriver'
  gem 'simplecov'
  gem 'typhoeus'
end

group(:development) do
  gem 'git-storyid'
  gem 'html2fortitude'
  gem 'letter_opener'
  gem 'meta_request'
  gem 'quiet_assets'
  gem 'spring-commands-rspec'
  gem 'spring'
  gem 'web-console'
  gem 'xray-rails'
end

**Comment by gleenn** [comment]
Okay, for some reason RubyGems is still not showing 0.9.5 for me yet.

I added

  gem 'fortitude', git: "git@github.com:ageweke/fortitude.git"

to my Gemfile to get the latest in the mean time, hopefully that helps someone else :).

**Comment by ajb** [comment]
Ah, gotcha. Pinging @ageweke: looks like `0.9.5` needs to be published to Rubygems.
