### ISSUE TITLE
use controller.view_paths to resolve view paths when calculating widget_class_from_file

### ISSUE THREAD

**Issue by leafo** [ageweke/fortitude#45]
in `fortitude/lib/fortitude/rails/template_handler.rb` you have `Rails.application.paths['app/views']`, which only searches path set via the configuration, and not ones added added at request time like those from `prepend_view_path`

`view_paths` can be used to get all the paths: http://api.rubyonrails.org/classes/ActionView/ViewPaths/ClassMethods.html#method-i-view_paths

The only issue with this is that it must be called in a request context, so the `TemplateHandler`'s call method needs to be updated to do the look up at render time.

**Comment by ageweke** [comment]
This has been fixed in 0.9.5, which I just released.
