### ISSUE TITLE
ArgumentError: wrong number of arguments (given 5, expected 4) with ActionView 4.2.6

### ISSUE THREAD

**Issue by gleenn** [ageweke/fortitude#55]
I'm getting explosions from the Fortitude railtie that's monkey-patching ActionView to help it autoload view classes. Looks like the monkey-patched method inside ActionView changed the method arity but Fortitude hasn't matched? I honestly don't really understand why my particular setup isn't working because I've used other Rails projects with higher and lower versions and didn't have problems.

I also hacked Fortitude gem source and added the missing method param, passing it straight through and got everything working properly.

I'm currently on Rails 4.2.6 and attempting to use Foritude 0.9.4.

Any advice would be appreciated!

ArgumentError:
       wrong number of arguments (given 5, expected 4)
     # /Users/glenn/.rvm/gems/ruby-2.3.1/gems/fortitude-0.9.4/lib/fortitude/rails/railtie.rb:251:in `find_templates_with_fortitude'
     # /Users/glenn/.rvm/gems/ruby-2.3.1/gems/actionmailer-4.2.6/lib/action_mailer/base.rb:914:in `each_template'
     # /Users/glenn/.rvm/gems/ruby-2.3.1/gems/actionmailer-4.2.6/lib/action_mailer/base.rb:900:in `collect_responses'
     # /Users/glenn/.rvm/gems/ruby-2.3.1/gems/actionmailer-4.2.6/lib/action_mailer/base.rb:829:in `mail'
     # ./app/mailers/application_mailer.rb:20:in `mail_with_defaults'
     # ./app/mailers/welcome_mailer.rb:4:in `welcome_member'

**Comment by ageweke** [comment]
Really easy answer: update to using the latest code (`gem “fortitude”, :git => ‘git://github.com/ageweke/fortitude.git'`), rather than release. 

I plan to publish a new version soon that includes this fix!

**Comment by gleenn** [comment]
Great, worked like a charm. Thanks!
