### ISSUE TITLE
Fortitude prevents Rails csrf_meta_tags from being rendered in the <head> element

### ISSUE THREAD

**Issue by alechoey** [ageweke/fortitude#58]
Rails renders the `csrf_meta_tags` helper as a text element seen [here](https://github.com/rails/rails/blob/master/actionview/lib/action_view/helpers/csrf_helper.rb)

Fortitude complains with an error
```
The widget #<_> tried to render an element that is not allowed by element nesting rules: you can't put a <_text> inside a <html>. (See 'http://www.w3.org/TR/html5/semantics.html#the-html-element' for more details.)
```

**Comment by evanwalsh** [comment]
@alechoey Did you ever find a solution for this?
